FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN apt-get update && apt-get install -y ffmpeg

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:80","--worker-class", "eventlet", "-w", "1", "app.main:app"]