services:
  musicvideogenerator:
    build:
      context: .
      dockerfile: Dockerfile  
      
    container_name: musicVideoGenerator
    
    environment:
      - GEVENT_SUPPORT=True

    ports:
      - 5000:80
    restart: unless-stopped